### ISSUE TITLE
Broken compatibility with Neos.Media < 4.2

### ISSUE THREAD

**Issue by ComiR** [neos/metadata-extractor#26]
https://github.com/neos/metadata-extractor/commit/ac99429b1d797db192ca6a160807c7b8facc2fd8 (from https://github.com/neos/metadata-extractor/pull/22) broke compatibility with Neos.Media < 4.2.

**Comment by kdambekalns** [comment]
@daniellienert Should be just raise the dependency? Or fix it with a check on the method being available?

**Comment by ComiR** [comment]
With a check, we could keep the compatibility and allow for older Neos instances to use the most recent version of this package.

If the dependency is raised, at least a bugfix release with that commit reverted is needed in addition to the usual (new major?) release.

**Comment by kdambekalns** [comment]
Added the check, after all it is in https://github.com/neos/metadata/pull/7 as well (for whatever reason I did not push the last two commits there until now, so thanks for this to make me aware!).
